import {TechnologyInterface} from '@/interfaces/technologyInterface';
import {SkillInterface} from '@/interfaces/skillInterface';

export interface UserInterface {
  id: number;
  username: string;
  firstName: string;
  lastName: string;
  firstNameRu: string;
  lastNameRu: string;
  email: string;
  phone: string;
  additionalPhone: string;
  gmailId: string;
  skypeId: string;
  facebookId: string;
  githubId: string;
  upworkId: string;
  bitbucketId: string;
  slackId: string;
  sshPublicKey: string;
  sshPublicKeyModified: string;
  level: string;
  gender: string;
  groups: any;
  isVacation: boolean;
  attachmentId: number;
  attachment: {
    id: number;
    name: string;
    originalName: string;
    link: string;
    link200: string;
    link48: string;
    link70: string;
  };
  workStartDate: string;
  workEndDate: string;
  birthDate: string;
  isActive: boolean;
  workPlace: string;
  profile: string;
  personalQualities: string;
  education: string;
  experience: string;
  languages: any;
  leadId: number;
  managerId: number;
  supervisorId: number;
  primarySalesManagerId: number;
  use2f: boolean;
  createdAt: string;
  updatedAt: string;
  tableNumber: string;
  filteredSkillName?: string;
  filteredSkillLvl?: string;
}
